runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: B748Oym4g/ug+mUGZAcMvKxFQU967zp0BSJEjb6rkvI=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie